### ISSUE TITLE
i trained model with 2000 images . but when i run it saying if HumanNames[best_class_indices[0]] == H_i: IndexError: list index out of range 

### ISSUE THREAD

**Issue by abhishek11cse134** [AISangam/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow#15]
i trained model with 2000 images . but when i run it saying if HumanNames[best_class_indices[0]] == H_i: IndexError: list index out of range 
Result Indices:  1872
HumanNames: ['Akshay Kumar', 'Nawazuddin Siddiqui', 'Salman Khan', 'Shahrukh Khan', 'Sunil Shetty', 'Sunny Deol']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/abhishekkumar/Downloads/face/test_image.py", line 130, in <module>
    if HumanNames[best_class_indices[0]] == H_i:
IndexError: list index out of range

**Comment by DineshRajanT** [comment]
How did you train your model?On what architecture and how

**Comment by shankarvishnu** [comment]
Follow this [comment](https://github.com/AISangam/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow/issues/16#issuecomment-632616661) to run it properly. Perhaps you have forgotten to delete all data from "pre-img" directory before starting the process.
