### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by yashwantram97** [AISangam/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow#17]
Image: ./train_img/nandhu/nandhuThuFeb2115:46:142019.jpg
No of Detected Face: 0
Unable to align "./train_img/nandhu/nandhuThuFeb2115:46:142019.jpg"
Image: ./train_img/nandhu/nandhuThuFeb2115:46:252019.jpg
No of Detected Face: 1
Traceback (most recent call last):
  File "data_preprocess.py", line 7, in <module>
    nrof_images_total,nrof_successfully_aligned=obj.collect_data()
  File "/home/s1th/Documents/focus/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow-master/preprocess.py", line 93, in collect_data
    scaled_temp = misc.imresize(cropped_temp, (image_size, image_size), interp='bilinear')
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 555, in imresize
    im = toimage(arr, mode=mode)
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 408, in toimage
    image = Image.frombytes(mode, shape, strdata)
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2412, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/s1th/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 811, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

i think there a problem with the misc.resize part in preprocessing.py

**Comment by shankarvishnu** [comment]
Delete all these type of images then it will poperly.
