### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'GPUOptions'

### ISSUE THREAD

**Issue by VAJHAHARIKA** [AISangam/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow#33]
I have changed nothing, I just tried running data_preprocess and I solved all the errors that occurred except this.. can you help?

Reloaded modules: preprocess, facenet, detect_face
Traceback (most recent call last):

  File "D:\Projects\Mini Project\Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow\data_preprocess.py", line 5, in <module>
    nrof_images_total,nrof_successfully_aligned=obj.collect_data()

  File "D:\Projects\Mini Project\Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow\preprocess.py", line 23, in collect_data
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)

AttributeError: module 'tensorflow' has no attribute 'GPUOptions'

**Comment by anhanhtdh01** [comment]
pip3 install tensorflow==1.14.0

**Comment by AIFry-Py3** [comment]
check this

https://stackoverflow.com/questions/55917154/module-tensorflow-has-no-attribute-gpuoptions
Very very late, but hoping it helps out other people looking for the answer to the same issue.
